env:
  global:
    - CC_TEST_REPORTER_ID=e2f093ec0ab71bc4fc72464902f6408f46ab601be057b3e090f9af8bb8c0c7c0
language: node_js
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run standard
  - npm run test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: npm
  email: support@persephony.com
  api_key:
    secure: R4BaKvobSBKpaLTffW+5GTIhlbgGTWkdFmSaqoT2C5XKKxaXX39Gh9MPD5XOxSIe5LU6C6sZVaQr+UTRW/e3VRRU0iSbCobgWIrUWmfYeTV7CUt1vlzWju+gVT59pduppakBoR+6d+x9SxbBrnqAvWY9XSyEDOZe0Wp5W788WFBwUAwJge8yETcUfm/OczwKaNPbMT/JHAEJ2qcURQ/zfyeyvoNnGf1RbEdEUFqEh6el+FqEkQAZxuWWDkiQqYdFsp6DZH5t82O1HYHTEEaPyWvSTh9E0VzdUYjON4emnkZEKq1s9nk4dQV3ojraOATZA2+Y7q5qOGk/r5ZHmqmwaHEtDI16wo14BOYnnXir97fVcwB7I7aOI/CAEPUcrIWONejOw82CU12WMnLhD9zv9nn1kKk2Bbusi8nR8uGklY1kg+zytE1IeTICer/CyCvIzMRyBRuBoa4DHDLDHZGZQGJWpso+1Z4e2RVtSMfDkHf2rjpjTpyVZd5O2KusjLHHIigkJ6FGlVO/PmhZYNZbgeVBHOZLZVSFJ9L/q2u06n7UxqqfN0dqddoWqHk5eziZFpVYIjTf7KyPZB8NWMPUJ/hLnasho4WOAg59X46c3FGmGC9NY+14b3AuWTuuXLVEHxMow6kAxLXmQ34LL33gUiWj3CgymMeOxr4e4t6HHQc=
  on:
    tags: true
    repo: PersephonyAPI/javascript-sdk
    branch: master
notifications:
  slack:
    secure: IJdigAKNUug9MpUPFfygXXQMi5JSTHl47U2o2VcNiqJ/slflryDJtebXqmwf4ymIOozrFLU6s2jQtHz4txWjEZg3xw+P01eCAgQau2VFkVZqYWeQPnpG8ZWal4RFYkmXa5R6AUklhb3MR0Mqg8o+yZf7FBMK1X1Zs2GBCp1x/FolHJVNNMJaIPq5h71A06BS61wtISjyNHQt5/ZiTRTvs+yCi2BG3g48P1QELloFVPNWhIo42qpoe7YfxwVY+8Qo5997K3ljaVHVpFeViKkv+ILRHzdT67phZXdUgsUd9sth0Qa0lqkZPW6MnGaXwkBNmzjvTehlhFOlvHzo1x2gW76lK0lYzxXxY2R0KH/ceKn8Cyi4SWWvpb1IZmMI/4s0qnNITM2j9rKZGV4i/YpYNVLG8byAjNu1/noQzaT4waajrGD6q+RFJEtoN3esigpN6MtOWPq9rL8rWpLXT2LQc1RM/awkJtV51rkLKLoAhxOFZGLEvCIWI6TacxFLrO5AV2BMn005+yDUCr5szpfH0Goj0TLHo8oQSGdIwWsxzUDkTvVBSRgRlxj4TDmViwDaUt06aA00xHkdA+EVgCP7TPaUvC2+CYkyk4pRHc42JszgKhfl93KX94ElLAOd/0OCRzHkZaQrFRl57Md1PW363JTVEZSzclTGUsMQFgMcowU=
